BLOCK_SIZE = 50
GRAVITY_CONSTANT = 0.2
DISPLAY_WIDTH = 1500
DISPLAY_HEIGHT = 900

class Colors:
    COLOR_RED = (255, 0, 0)
    COLOR_GREEN = (0, 255, 0)
    COLOR_BLUE = (0, 0, 255)

    COLORS = {'RED': COLOR_RED, 'GREEN': COLOR_GREEN, 'BLUE': COLOR_BLUE}


class Direction:
    TOP_DIRECTION = -2
    BOTTOM_DIRECTIOM = 2
    RIGHT_DIRECTION = 1
    LEFT_DIRECTION = -1